import Midterm_Quiz1

class PersonInformationDisplay(Midterm_Quiz1.PersonInformation):
    def __init__(self):
        super().__init__()
        self.computation()

    def persondisplay(self):
        # Output of the Bill
        print("=================================================================================")
        print("--- Bill Information ---")
        print(f"Full Name: {self.person_name}")
        print(f"Street Address: {self.street_address}")
        print(f"Barangay: {self.barangay}")
        print(f"City Address: {self.city_address}")
        print(f"Province: {self.province}")
        print("=================================================================================")
        print(f"Balance from the Previous Billing: {self.balance_previous:.2f}, Remarks: {self.remarks}")
        print("=================================================================================")
        print("--- Current Charges ---")
        print(f"Amount Due: {self.total_current_amount:.2f}")
        print(f"Due Date: {self.due_date}")
        print("=================================================================================")
        print(f"Total Amount Due: {self.total_amount_due:.2f}")
        print("=================================================================================")
        print("--- Service Info ---")
        print(f"Service ID Number: {self.service_id_number}")
        print(f"Rate: {self.rate}")
        print(f"Contract in the name of: {self.person_name}")
        print(f"Service Address: {self.street_address}, {self.barangay}, {self.city_address}, {self.province}")
        print("=================================================================================")
        print("--- Billing Info ---")
        print(f"Bill Date: {self.bill_date}")
        print(f"Meter Reading Date: {self.meter_reading_date}")
        print(f"Bill Period: {self.bill_period}")
        print(f"Total KWH: {self.total_kwh}")
        print(f"Total Current Amount: {self.total_current_amount:.2f}")
        print(f"Next Meter Reading: {self.next_meter_reading}")
        print("=================================================================================")
        print(f"Customer Account Number (CAN): {self.service_id_number}")
        print(f"Please Pay: {self.total_amount_due:.2f}")
        print("=================================================================================")
        print("--- Bill Computation Summary---")
        print(f"Remaining Balance from the Previous Bill: {self.balance_previous:.2f}")
        print(f"Charges for this billing period: {self.billing_period:.2f}")
        print(f"Generation: {self.generation:.2f}")
        print(f"Transmission: {self.transmission:.2f}")
        print(f"System Loss: {self.system_loss:.2f}")
        print(f"Distribution (Meralco): {self.distribution:.2f}")
        print(f"Subsidies: {self.subsidies:.2f}")
        print(f"Government Taxes: {self.government_taxes:.2f}")
        print(f"Universal Charges: {self.universal_charges:.2f}")
        print(f"FiT-AN (Renewable): {self.fit_an:.2f}")
        print(f"Applied Credits: {self.applied_credits:.2f}")
        print(f"Other Charges: {self.other_charges:.2f}")
        print(f"Installment Due: {self.installment_due:.2f}")
        print(f"Total Amount Due: {self.total_amount_due:.2f}")
        print("=================================================================================")

#Instance of PersonInformationDisplay
person = PersonInformationDisplay()

# Call the display
person.persondisplay()